#include <frams/genetics/defgenoconv.h>
#include <frams/model/model.h>
#include <frams/model/modelparts.h>
#include <frams/util/multimap.h>
#include <frams/util/multirange.h>
#include <frams/genetics/geno.h>
#include <frams/genetics/genman.h>
#include <frams/genetics/preconfigured.h>
#include <frams/canvas/nn_layout_model.h>
#include <frams/genetics/genooperators.h>
#include <frams/genetics/fH/fH_oper.h>
#include <frams/genetics/fB/fB_oper.h>
#include <frams/genetics/fL/fL_oper.h>
#include <frams/genetics/f4/f4_oper.h>
#include <frams/genetics/f9/f9_oper.h>
#include <frams/genetics/fF/fF_oper.h>
#include <common/loggers/loggers.h>
#include <frams/param/param.h>
#include <frams/param/paramtree.h>
#include <frams/param/mutableparam.h>
#include <frams/_demos/genotypemini.h>
#include "js_types.h"
#include "js_interface_impl.cpp"
